### ISSUE TITLE
Fails to handle hunk header without target length

### ISSUE THREAD

**Issue by aelred** [messense/unidiff-rs#2]
I have a Git diff (from the GitHUB API) like so:

```
diff --git a/dummyfile.txt b/dummyfile.txt
new file mode 100644
index 0000000..421376d
--- /dev/null
+++ b/dummyfile.txt
@@ -0,0 +1 @@
+dummy
```

Which panics:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
...
at /.../github.com-1ecc6299db9ec823/unidiff-0.3.1/src/lib.rs:350
```

It looks like the library is expecting another number with the `+1` in `@@ -0,0 +1 @@`. I don't know if this is a valid diff or not.

**Comment by unidevel** [comment]
Also failed with one line file when parsing `@@ -1 +1 @@`
